GET http://localhost:4000/

###
GET http://localhost:4000/users

###
GET http://localhost:4000/users/5d1fdaf4c9f32428e881bbc1

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "username": "Rhinestone Cowboy"
}

###
DELETE http://localhost:4000/users/5d1fde66c152e835ac546513

###
PATCH  http://localhost:4000/users/5d1fdaf4c9f32428e881bbc1
Content-Type: application/json

{
    "username": "Cormac McCarthy"
}
