GET http://localhost:4000/charts

###


GET http://localhost:4000/charts/5e9b786e4543f623f01a8e86

###

POST http://localhost:4000/charts
Content-Type: application/json

{
"title": "title4",
"description": "getting there"
}

###

PATCH http://localhost:4000/charts/5e9b78a94543f623f01a8e87
Content-Type: application/json

{ 
   "description": "lets see if this works."
}

###

DELETE http://localhost:4000/charts/5e9b786e4543f623f01a8e86

###