GET http://localhost:4000/maplogentry

###

POST http://localhost:4000/maplogentry
Content-Type: application/json

{
 "title": "Burj Khalifa", 
 "description": "The Burj Khalifa (Arabic: برج خليفة‎, Arabic for Khalifa Tower; pronounced English: /ˈbɜːrdʒ kəˈliːfə/), known as the Burj Dubai prior to its inauguration in 2010, is a skyscraper in Dubai, United Arab Emirates. With a total height of 829.8 m (2,722 ft) and a roof height (excluding antenna, but including a 244 m spire[3]) of 828 m (2,717 ft), the Burj Khalifa has been the tallest structure and building in the world since its topping out in 2009.",
 "image": "https://upload.wikimedia.org/wikipedia/en/thumb/9/93/Burj_Khalifa.jpg/240px-Burj_Khalifa.jpg",
 "latitude": 25.11497,
 "longitude": 55.1626   
}