GET http://localhost:4000/users

###

GET http://localhost:4000/users/5d272e4f2f7ce03fe41bc108

###

POST http://localhost:4000/users
Content-Type: application/json

{
"username": "Andre Giant"   
}

###

DELETE http://localhost:4000/users/5df1899fa644194110cbddcb

###

PATCH http://localhost:4000/users/5df1890d1fb9b64734889597
Content-Type: application/json

{
"username": "Andre Giant"   
}