GET http://localhost:4000/users

###

GET http://localhost:4000/users/5df1890d1fb9b64734889597

###

POST http://localhost:4000/users
Content-Type: application/json

{
"username": "Snoop Dogg"   
}

###

DELETE http://localhost:4000/users/5df18779c78bfd2610543b8f

###

PATCH http://localhost:4000/users/5df1890d1fb9b64734889597
Content-Type: application/json

{
"username": "Andre the Giant"   
}